### ISSUE TITLE
Literal dot in key

### ISSUE THREAD

**Issue by madstap** [binaryage/cljs-oops#11]
I'm dealing with an api that faux namespace their keys with a dot as the namespace separator; example: `{"home-page.main-image": {...}}`. cljs-oops thinks dots are nested objects. Is there a workaround for this, or should I just use goog.object with this api?

**Comment by darwin** [comment]
You would have to escape the dots.

Look here for some inspiration:
https://github.com/binaryage/cljs-oops/blob/master/test/src/tests/oops/main.cljs#L155-L174
