### ISSUE TITLE
Escaping special symbols

### ISSUE THREAD

**Issue by piranha** [binaryage/cljs-oops#15]
I'm using SheetJS in some project and I need to retrieve data from `obj["!ref"]`. Doing `(oget obj "!ref")` obviously warns me about punching and still generates code about it. Right now I've reverted to using `aget`, but still it would be nice to handle that case. :)

P.S. Hi! :)

**Comment by darwin** [comment]
Throw slashes at it, don't remember details, but it should work:
https://github.com/binaryage/cljs-oops/blob/master/test/src/tests/oops/main.cljs#L182-L197

**Comment by piranha** [comment]
Ah, two backslashes! Okay, thanks, with one backslash compiler complains.

**Comment by darwin** [comment]
Well, technically it is one backslash in the string. But you have write two to get a single one in clojure/java string. If you were to read that selector string from a file or construct it pragmatically you would use only one backslash.
