### ISSUE TITLE
Diagnostics: check for frozen objects when attempting `oset`

### ISSUE THREAD

**Issue by darwin** [binaryage/cljs-oops#16]
Unexpectedly dealing with frozen objects could cause a lot of confusion. We should check for frozen objects in dev mode and give user a friendly, descriptive warning.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/isFrozen

**Comment by donmullen** [comment]
Also Object.seal
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/seal
