### ISSUE TITLE
Error thrown when using oops with js/Date objects

### ISSUE THREAD

**Issue by efraimmgon** [binaryage/cljs-oops#24]
When entering the code

```clojure
(def d (js/Date.))
(oops/ocall d "toISOString")
```
I am getting the error

`Oops, Unexpected object value (date-like) #object[devtools.toolbox.t_devtools$toolbox78167]`

What gives?

**Comment by darwin** [comment]
Please see issue #13. It is the same problem.

**Comment by efraimmgon** [comment]
Nice. Thanks!

**Comment by efraimmgon** [comment]
Just would like to add this as an afterthought:

Is there a reason we can't have the erro msg be more clear? There probably will be more looks like me in the future.
