### ISSUE TITLE
Thanks for Oops!

### ISSUE THREAD

**Issue by theronic** [binaryage/cljs-oops#25]
Hey Binaryage, just want to say thanks for Oops, because man this just saved my butt working on my Cljs-based [lockdown project](https://www.tradebridge.app/).

I was having a hard time with name-mangling even with `:optimizations :simple` interfacing with Algolia, and `ocall` worked straight away. I feel like this should be part of the standard Cljs interop.

Cheers
P.

**Comment by darwin** [comment]
Thanks. I'm glad it helped.

I would recommend looking into https://github.com/applied-science/js-interop as well. 
If js-interop library had existed at the time I would not write oops.
