### ISSUE TITLE
Setup automated testing against Chrome

### ISSUE THREAD

**Issue by darwin** [binaryage/cljs-oops#3]
It would be nice to setup chromedriver to exercise tests against real chrome as well. Some [javascript hackery](https://github.com/binaryage/cljs-oops/blob/a83b25f327a846b7f4c8085424e4ec5648038825/test/src/tests/oops/main.cljs#L455-L481) we employ works only under chrome.

It can be done. I have done it [once](https://github.com/binaryage/dirac/tree/master/test/browser/src/dirac) for Dirac. But it is quite non-trivial work to get right.

**Comment by dijonkitchen** [comment]
Maybe this would be useful? https://github.com/GoogleChrome/puppeteer

**Comment by darwin** [comment]
Yep, anything like that would work. 

But this task has a very low priority, because it's been 2+ years and I don't see a strong need for this. The browser-sensitive code works and I haven't touched it since.
