### ISSUE TITLE
purpose of ocall! and oapply!

### ISSUE THREAD

**Issue by jiangts** [binaryage/cljs-oops#6]
I was reading the docs and didn't get any good examples of using `ocall!` and `oapply!`

How are they different from the normal `ocall` and `oapply`?

**Comment by darwin** [comment]
They are the same. It is just for you to express that you are calling a side-effecting function.

https://github.com/binaryage/cljs-oops/blob/d530a3cdf8cbab39bd2699c36caded4414224c50/src/lib/oops/core.clj#L48
